var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/auth/logout/route.js")
R.c("server/chunks/src_1q57rcs._.js")
R.c("server/chunks/[root-of-the-server]__0h3ohrn._.js")
R.c("server/chunks/[root-of-the-server]__1sdgs2d._.js")
R.c("server/chunks/_2143kk3._.js")
R.c("server/chunks/[root-of-the-server]__0oxznu7._.js")
R.c("server/chunks/src_1akg35a._.js")
R.c("server/chunks/node_modules_next_1_14bcs._.js")
R.c("server/chunks/node_modules_next_dist_13kw1hb._.js")
R.c("server/chunks/node_modules_next_1zdbrne._.js")
R.c("server/chunks/_next-internal_server_app_api_auth_logout_route_actions_0regwyr.js")
R.m(683932)
module.exports=R.m(683932).exports
