var R=require("../../../../../chunks/[turbopack]_runtime.js")("server/app/api/tools/agent-bridge/tproxy/route.js")
R.c("server/chunks/[root-of-the-server]__19ujnqf._.js")
R.c("server/chunks/[root-of-the-server]__1sdgs2d._.js")
R.c("server/chunks/[root-of-the-server]__209t511._.js")
R.c("server/chunks/src_1jregdf._.js")
R.c("server/chunks/_0g70cbn._.js")
R.c("server/chunks/[root-of-the-server]__0oxznu7._.js")
R.c("server/chunks/_next-internal_server_app_api_tools_agent-bridge_tproxy_route_actions_0q9uds0.js")
R.m(792076)
module.exports=R.m(792076).exports
