"""initial_schema

Revision ID: 1c4268b181f5
Revises: 
Create Date: 2026-07-03 11:38:18.314396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c4268b181f5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_target_scopes_id'), table_name='target_scopes')
    op.drop_table('target_scopes')
    op.drop_index(op.f('ix_rastro_config_id'), table_name='rastro_config')
    op.drop_index(op.f('ix_rastro_config_key'), table_name='rastro_config')
    op.drop_table('rastro_config')
    op.drop_index(op.f('ix_targets_intel_id'), table_name='targets_intel')
    op.drop_table('targets_intel')
    op.drop_constraint(None, 'delivery_records', type_='foreignkey')
    op.create_foreign_key(None, 'delivery_records', 'notifications', ['notification_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_endpoints_target_id'), 'endpoints', ['target_id'], unique=False)
    op.drop_constraint(None, 'endpoints', type_='foreignkey')
    op.create_foreign_key(None, 'endpoints', 'targets', ['target_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'evidence', type_='foreignkey')
    op.drop_constraint(None, 'evidence', type_='foreignkey')
    op.create_foreign_key(None, 'evidence', 'endpoints', ['endpoint_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'evidence', 'verdicts', ['verdict_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_findings_target_id'), 'findings', ['target_id'], unique=False)
    op.drop_constraint(None, 'findings', type_='foreignkey')
    op.drop_constraint(None, 'findings', type_='foreignkey')
    op.create_foreign_key(None, 'findings', 'endpoints', ['endpoint_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'findings', 'targets', ['target_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'investigations', type_='foreignkey')
    op.create_foreign_key(None, 'investigations', 'targets', ['target_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_memory_records_category'), 'memory_records', ['category'], unique=False)
    op.create_index(op.f('ix_memory_records_key'), 'memory_records', ['key'], unique=False)
    op.drop_constraint(None, 'pipeline_runs', type_='foreignkey')
    op.create_foreign_key(None, 'pipeline_runs', 'targets', ['target_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'quick_wins', type_='foreignkey')
    op.create_foreign_key(None, 'quick_wins', 'targets', ['target_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'report_versions', type_='foreignkey')
    op.create_foreign_key(None, 'report_versions', 'reports', ['report_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_reports_program'), 'reports', ['program'], unique=False)
    op.create_index(op.f('ix_reports_status'), 'reports', ['status'], unique=False)
    op.create_index(op.f('ix_reports_target'), 'reports', ['target'], unique=False)
    op.drop_constraint(None, 'reports', type_='foreignkey')
    op.create_foreign_key(None, 'reports', 'investigations', ['investigation_id'], ['id'], ondelete='SET NULL')
    op.alter_column('scan_runs', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('scan_runs', 'endpoint_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_scan_runs_target_id'), 'scan_runs', ['target_id'], unique=False)
    op.drop_constraint(None, 'scan_runs', type_='foreignkey')
    op.create_foreign_key(None, 'scan_runs', 'targets', ['target_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'submission_records', type_='foreignkey')
    op.create_foreign_key(None, 'submission_records', 'reports', ['report_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'target_identities', type_='foreignkey')
    op.create_foreign_key(None, 'target_identities', 'targets', ['target_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'target_sessions', type_='foreignkey')
    op.create_foreign_key(None, 'target_sessions', 'target_identities', ['identity_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_targets_name'), 'targets', ['name'], unique=False)
    op.drop_constraint(None, 'validation_results', type_='foreignkey')
    op.create_foreign_key(None, 'validation_results', 'verdicts', ['verdict_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'validation_runs', type_='foreignkey')
    op.drop_constraint(None, 'validation_runs', type_='foreignkey')
    op.drop_constraint(None, 'validation_runs', type_='foreignkey')
    op.drop_constraint(None, 'validation_runs', type_='foreignkey')
    op.drop_constraint(None, 'validation_runs', type_='foreignkey')
    op.create_foreign_key(None, 'validation_runs', 'verdicts', ['verdict_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'validation_runs', 'target_identities', ['identity_probe_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'validation_runs', 'endpoints', ['endpoint_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'validation_runs', 'target_identities', ['identity_baseline_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'validation_runs', 'investigations', ['investigation_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(None, 'verdicts', type_='foreignkey')
    op.create_foreign_key(None, 'verdicts', 'endpoints', ['endpoint_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'verdicts', type_='foreignkey')
    op.create_foreign_key(None, 'verdicts', 'endpoints', ['endpoint_id'], ['id'])
    op.drop_constraint(None, 'validation_runs', type_='foreignkey')
    op.drop_constraint(None, 'validation_runs', type_='foreignkey')
    op.drop_constraint(None, 'validation_runs', type_='foreignkey')
    op.drop_constraint(None, 'validation_runs', type_='foreignkey')
    op.drop_constraint(None, 'validation_runs', type_='foreignkey')
    op.create_foreign_key(None, 'validation_runs', 'investigations', ['investigation_id'], ['id'])
    op.create_foreign_key(None, 'validation_runs', 'verdicts', ['verdict_id'], ['id'])
    op.create_foreign_key(None, 'validation_runs', 'endpoints', ['endpoint_id'], ['id'])
    op.create_foreign_key(None, 'validation_runs', 'target_identities', ['identity_baseline_id'], ['id'])
    op.create_foreign_key(None, 'validation_runs', 'target_identities', ['identity_probe_id'], ['id'])
    op.drop_constraint(None, 'validation_results', type_='foreignkey')
    op.create_foreign_key(None, 'validation_results', 'verdicts', ['verdict_id'], ['id'])
    op.drop_index(op.f('ix_targets_name'), table_name='targets')
    op.drop_constraint(None, 'target_sessions', type_='foreignkey')
    op.create_foreign_key(None, 'target_sessions', 'target_identities', ['identity_id'], ['id'])
    op.drop_constraint(None, 'target_identities', type_='foreignkey')
    op.create_foreign_key(None, 'target_identities', 'targets', ['target_id'], ['id'])
    op.drop_constraint(None, 'submission_records', type_='foreignkey')
    op.create_foreign_key(None, 'submission_records', 'reports', ['report_id'], ['id'])
    op.drop_constraint(None, 'scan_runs', type_='foreignkey')
    op.create_foreign_key(None, 'scan_runs', 'targets', ['target_id'], ['id'])
    op.drop_index(op.f('ix_scan_runs_target_id'), table_name='scan_runs')
    op.alter_column('scan_runs', 'endpoint_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('scan_runs', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(None, 'reports', type_='foreignkey')
    op.create_foreign_key(None, 'reports', 'investigations', ['investigation_id'], ['id'])
    op.drop_index(op.f('ix_reports_target'), table_name='reports')
    op.drop_index(op.f('ix_reports_status'), table_name='reports')
    op.drop_index(op.f('ix_reports_program'), table_name='reports')
    op.drop_constraint(None, 'report_versions', type_='foreignkey')
    op.create_foreign_key(None, 'report_versions', 'reports', ['report_id'], ['id'])
    op.drop_constraint(None, 'quick_wins', type_='foreignkey')
    op.create_foreign_key(None, 'quick_wins', 'targets', ['target_id'], ['id'])
    op.drop_constraint(None, 'pipeline_runs', type_='foreignkey')
    op.create_foreign_key(None, 'pipeline_runs', 'targets', ['target_id'], ['id'])
    op.drop_index(op.f('ix_memory_records_key'), table_name='memory_records')
    op.drop_index(op.f('ix_memory_records_category'), table_name='memory_records')
    op.drop_constraint(None, 'investigations', type_='foreignkey')
    op.create_foreign_key(None, 'investigations', 'targets', ['target_id'], ['id'])
    op.drop_constraint(None, 'findings', type_='foreignkey')
    op.drop_constraint(None, 'findings', type_='foreignkey')
    op.create_foreign_key(None, 'findings', 'endpoints', ['endpoint_id'], ['id'])
    op.create_foreign_key(None, 'findings', 'targets', ['target_id'], ['id'])
    op.drop_index(op.f('ix_findings_target_id'), table_name='findings')
    op.drop_constraint(None, 'evidence', type_='foreignkey')
    op.drop_constraint(None, 'evidence', type_='foreignkey')
    op.create_foreign_key(None, 'evidence', 'endpoints', ['endpoint_id'], ['id'])
    op.create_foreign_key(None, 'evidence', 'verdicts', ['verdict_id'], ['id'])
    op.drop_constraint(None, 'endpoints', type_='foreignkey')
    op.create_foreign_key(None, 'endpoints', 'targets', ['target_id'], ['id'])
    op.drop_index(op.f('ix_endpoints_target_id'), table_name='endpoints')
    op.drop_constraint(None, 'delivery_records', type_='foreignkey')
    op.create_foreign_key(None, 'delivery_records', 'notifications', ['notification_id'], ['id'])
    op.create_table('targets_intel',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('domain', sa.VARCHAR(), nullable=True),
    sa.Column('source', sa.VARCHAR(), nullable=True),
    sa.Column('program_url', sa.VARCHAR(), nullable=True),
    sa.Column('quality_score', sa.INTEGER(), nullable=True),
    sa.Column('complexity_score', sa.INTEGER(), nullable=True),
    sa.Column('roi_score', sa.INTEGER(), nullable=True),
    sa.Column('noise_score', sa.INTEGER(), nullable=True),
    sa.Column('freshness_score', sa.FLOAT(), nullable=True),
    sa.Column('competition_score', sa.FLOAT(), nullable=True),
    sa.Column('opportunity_score', sa.FLOAT(), nullable=True),
    sa.Column('reward_score', sa.FLOAT(), nullable=True),
    sa.Column('reward_confidence', sa.FLOAT(), nullable=True),
    sa.Column('attack_surface_score', sa.FLOAT(), nullable=True),
    sa.Column('evidence_potential_score', sa.FLOAT(), nullable=True),
    sa.Column('saas_probability', sa.FLOAT(), nullable=True),
    sa.Column('api_density', sa.INTEGER(), nullable=True),
    sa.Column('graphql_detected', sa.BOOLEAN(), nullable=True),
    sa.Column('b2b_indicator', sa.BOOLEAN(), nullable=True),
    sa.Column('admin_detected', sa.BOOLEAN(), nullable=True),
    sa.Column('multi_tenant', sa.BOOLEAN(), nullable=True),
    sa.Column('tags', sa.VARCHAR(), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('technology_tags', sa.VARCHAR(), server_default=sa.text("('')"), nullable=True),
    sa.Column('cms_detected', sa.VARCHAR(), nullable=True),
    sa.Column('framework_detected', sa.VARCHAR(), nullable=True),
    sa.Column('wordpress_plugins_detected', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_targets_intel_id'), 'targets_intel', ['id'], unique=False)
    op.create_table('rastro_config',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('key', sa.VARCHAR(), nullable=False),
    sa.Column('value', sa.TEXT(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rastro_config_key'), 'rastro_config', ['key'], unique=1)
    op.create_index(op.f('ix_rastro_config_id'), 'rastro_config', ['id'], unique=False)
    op.create_table('target_scopes',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('target_id', sa.INTEGER(), nullable=False),
    sa.Column('scope_text', sa.VARCHAR(), nullable=False),
    sa.Column('is_wildcard', sa.BOOLEAN(), nullable=True),
    sa.Column('is_api', sa.BOOLEAN(), nullable=True),
    sa.Column('is_graphql', sa.BOOLEAN(), nullable=True),
    sa.Column('extracted_domain', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['target_id'], ['targets_intel.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_target_scopes_id'), 'target_scopes', ['id'], unique=False)
    # ### end Alembic commands ###
