kestra:
  server:
    basic-auth:
      enabled: true
      users:
        - username: ownex
          password: "${{ env.KESTRA_PASSWORD ?? 'change-me' }}"
  queues:
    type: h2
  repository:
    type: h2
  storage:
    type: local
    local:
      base-path: /app/storage
