"""Hypothesis → Finding Bridge (PROMOTE stage).

Takes vulnerability hypotheses generated by the HYPOTHESIS stage,
runs them through the HTTP Probe Engine to test them against real endpoints,
and promotes confirmed hypotheses to Finding records in the database.

This is the critical bridge that closes the gap between:
  HYPOTHESIS → [PROMOTE] → VALIDATE → REPORT
"""

from __future__ import annotations

import json
import logging
import time
from typing import Any

from database import models

logger = logging.getLogger("ownex.pipeline.hypothesis_bridge")

VULN_TYPE_MAP: dict[str, str] = {
    "idor": "idor",
    "ssrf": "ssrf",
    "xss": "xss",
    "sqli": "sqli",
    "auth_bypass": "auth_bypass",
    "file_upload": "file_upload",
    "graphql_injection": "graphql_injection",
    "broken_access_control": "idor",
    "injection": "sqli",
    "path_traversal": "idor",
}

CONFIDENCE_THRESHOLD = 0.5


def _get_vuln_type(hypothesis: Any) -> str:
    """Extract vulnerability type from a hypothesis object."""
    vt = getattr(hypothesis, "vulnerability_type", None)
    if vt is None:
        return "unknown"
    if isinstance(vt, str):
        key = vt.lower().replace(" ", "_")
    else:
        key = vt.value.lower().replace(" ", "_") if hasattr(vt, "value") else str(vt).lower()
    return VULN_TYPE_MAP.get(key, key)


def _get_hypothesis_details(hypothesis: Any) -> dict[str, Any]:
    """Extract a dict of hypothesis fields for logging."""
    return {
        "id": getattr(hypothesis, "id", "?"),
        "vuln_type": _get_vuln_type(hypothesis),
        "confidence": getattr(hypothesis, "confidence", 0.0),
        "priority": getattr(hypothesis, "priority_score", 0.0),
    }


def _build_endpoint_url(target: Any, endpoint: Any) -> str:
    """Build a full URL from target domain and endpoint path."""
    domain = getattr(target, "domain", "") or getattr(target, "name", "")
    path = getattr(endpoint, "path", "/") or "/"
    if not path.startswith("/"):
        path = "/" + path
    if domain:
        return f"https://{domain}{path}"
    return path


def _publish_event(event_type: str, payload: dict[str, Any]) -> None:
    """Publish an event to the EventBus."""
    try:
        from cores.events.event_bus import get_event_bus

        bus = get_event_bus()
        bus.publish(event_type, **payload)
    except Exception:
        logger.debug("EventBus not available, skipping event: %s", event_type)


def _create_finding(
    session: Any, endpoint: Any, target: Any, analysis: Any, hypothesis_id: str
) -> models.Finding | None:
    """Create a Finding record in the database from a confirmed probe result."""
    try:
        confidence = getattr(analysis, "confidence", 0.0)
        status = getattr(analysis, "status", "unknown")

        evidence_items = getattr(analysis, "evidence_items", [])
        snippets = getattr(analysis, "snippets", [])
        indicators = getattr(analysis, "indicators", [])
        poc_data = getattr(analysis, "poc_data", {})
        req_resp_pairs = getattr(analysis, "request_response_pairs", [])

        evidence_text = json.dumps(
            {
                "evidence_items": evidence_items[:5],
                "snippets": snippets[:5],
                "indicators": indicators[:5],
                "poc_data": poc_data,
                "request_response_pairs": req_resp_pairs[:2],
                "hypothesis_id": hypothesis_id,
            },
            indent=2,
            default=str,
        )

        title_parts = [f"[{status.upper()}] {analysis.vulnerability_type}"]
        if snippets:
            title_parts.append(f" — {snippets[0][:120]}")
        title = "".join(title_parts)[:255]

        finding = models.Finding(
            target_id=target.id,
            endpoint_id=endpoint.id,
            title=title,
            severity=_confidence_to_severity(confidence),
            description=evidence_text[:5000],
            status="open",
            vulnerability_type=_get_vuln_type(analysis) if hasattr(analysis, "vulnerability_type") else "unknown",
        )
        session.add(finding)
        session.commit()
        session.refresh(finding)

        logger.info(
            "[PROMOTE] Finding #%d created (hypothesis=%s vuln=%s confidence=%.3f)",
            finding.id,
            hypothesis_id,
            finding.vulnerability_type,
            confidence,
        )

        _publish_event(
            "finding:created",
            {
                "finding_id": finding.id,
                "target_id": target.id,
                "vulnerability_type": finding.vulnerability_type,
                "severity": finding.severity,
                "confidence": confidence,
                "source": "hypothesis_bridge",
            },
        )

        return finding

    except Exception as e:
        logger.exception("[PROMOTE] Failed to create finding for hypothesis %s: %s", hypothesis_id, e)
        session.rollback()
        return None


def _confidence_to_severity(confidence: float) -> str:
    if confidence >= 0.8:
        return "critical"
    if confidence >= 0.6:
        return "high"
    if confidence >= 0.4:
        return "medium"
    return "low"


def run_promote(session: Any) -> dict[str, Any]:
    """Run the PROMOTE stage.

    For each endpoint with a hypothesis_id but no corresponding Finding,
    probes the endpoint using the HTTP Probe Engine and creates a Finding
    if the probe confirms the vulnerability.

    Returns a summary dict with counts.
    """
    from core.http_probe.engine import ProbeEngine

    start = time.time()
    stats: dict[str, Any] = {
        "endpoints_checked": 0,
        "hypotheses_tested": 0,
        "findings_created": 0,
        "evidence_bundles": 0,
        "reports_generated": 0,
        "skipped_no_vuln_type": 0,
        "failed": 0,
        "errors": [],
    }

    endpoints = session.query(models.Endpoint).filter(models.Endpoint.hypothesis_id.isnot(None)).limit(100).all()
    stats["endpoints_checked"] = len(endpoints)

    if not endpoints:
        logger.info("[PROMOTE] No endpoints with pending hypotheses")
        return stats

    # Check which endpoints already have findings to avoid duplicates
    endpoint_ids_with_findings = {
        r[0]
        for r in session.query(models.Finding.endpoint_id)
        .filter(models.Finding.endpoint_id.isnot(None))
        .distinct()
        .all()
    }

    engine = ProbeEngine()

    for ep in endpoints:
        if ep.id in endpoint_ids_with_findings:
            logger.debug("[PROMOTE] Endpoint %d already has findings, skipping", ep.id)
            continue

        target = session.query(models.Target).filter(models.Target.id == ep.target_id).first()
        if not target:
            logger.debug("[PROMOTE] Target %d not found for endpoint %d", ep.target_id, ep.id)
            continue

        # We need the original hypothesis to know the vulnerability type
        # Hypothesis ID is stored on the endpoint
        hypothesis_id = ep.hypothesis_id
        if not hypothesis_id:
            continue

        # Try to retrieve the hypothesis from the DB or infer type from endpoint data
        vuln_type = _infer_vuln_type_from_endpoint(ep, target)

        if not vuln_type:
            stats["skipped_no_vuln_type"] += 1
            logger.debug("[PROMOTE] No vulnerability type for endpoint %d (hypothesis=%s)", ep.id, hypothesis_id)
            continue

        url = _build_endpoint_url(target, ep)
        params = ep.parsed_params if hasattr(ep, "parsed_params") else {}
        method = getattr(ep, "method", "GET")

        logger.info(
            "[PROMOTE] Probing hypothesis=%s vuln=%s %s %s",
            hypothesis_id,
            vuln_type,
            method,
            url,
        )

        try:
            analysis = engine.probe(
                hypothesis_id=hypothesis_id,
                endpoint=url,
                method=method,
                vulnerability_type=vuln_type,
                params=params if params else None,
            )

            stats["hypotheses_tested"] += 1

            status = getattr(analysis, "status", "unknown")
            confidence = getattr(analysis, "confidence", 0.0)

            if status == "confirmed" and confidence >= CONFIDENCE_THRESHOLD:
                finding = _create_finding(session, ep, target, analysis, hypothesis_id)
                if finding:
                    stats["findings_created"] += 1
                    # Compose evidence with real probe data
                    bundle = _compose_evidence_for_finding(session, finding, ep, target, analysis)
                    if bundle:
                        stats["evidence_bundles"] += 1
                        # Generate report for confirmed finding
                        report = _generate_report_for_finding(session, finding, bundle)
                        if report:
                            stats["reports_generated"] += 1
            else:
                logger.info(
                    "[PROMOTE] Hypothesis %s not confirmed (status=%s confidence=%.3f)",
                    hypothesis_id,
                    status,
                    confidence,
                )

        except Exception as e:
            logger.exception("[PROMOTE] Probe failed for hypothesis %s: %s", hypothesis_id, e)
            stats["failed"] += 1
            stats["errors"].append(str(e))

    engine.close()
    elapsed = time.time() - start
    stats["elapsed_seconds"] = round(elapsed, 2)

    if stats["findings_created"] > 0:
        _publish_event(
            "pipeline:promote:completed",
            {
                "findings_created": stats["findings_created"],
                "evidence_bundles": stats["evidence_bundles"],
                "reports_generated": stats["reports_generated"],
                "hypotheses_tested": stats["hypotheses_tested"],
                "endpoints_checked": stats["endpoints_checked"],
                "elapsed_seconds": elapsed,
            },
        )

    logger.info(
        "[PROMOTE] Complete: %d hypotheses tested, %d findings, %d evidence, %d reports in %.1fs",
        stats["hypotheses_tested"],
        stats["findings_created"],
        stats["evidence_bundles"],
        stats["reports_generated"],
        elapsed,
    )

    return stats


def _compose_evidence_for_finding(
    session: Any,
    finding: models.Finding,
    endpoint: Any,
    target: Any,
    analysis: Any,
) -> dict[str, Any] | None:
    """Compose evidence bundle with real probe data and persist to DB."""
    try:
        from cores.evidence.composer import EvidenceComposer
        from cores.offensive.models import Hypothesis as HypModel

        vuln_type = getattr(analysis, "vulnerability_type", "generic")
        confidence = getattr(analysis, "confidence", 0.5)
        cvss = getattr(analysis, "cvss_estimate", 5.0)

        hyp_model = HypModel(
            id=finding.title or f"hyp-{finding.id}",
            vulnerability_type=vuln_type,
            endpoint=getattr(endpoint, "path", "/"),
            method=getattr(endpoint, "method", "GET"),
            parameters_of_interest=list(
                endpoint.parsed_params.keys() if hasattr(endpoint, "parsed_params") and endpoint.parsed_params else []
            ),
            summary=f"{vuln_type} vulnerability confirmed",
            description=getattr(analysis, "indicators", [""])[0] if getattr(analysis, "indicators", []) else "",
            confidence=confidence,
            severity=_confidence_to_severity(confidence),
        )

        composer = EvidenceComposer()
        bundle = composer.compose(
            hyp_model,
            host=f"://{target.domain}" if hasattr(target, "domain") else "",
            probe_analysis=analysis,
        )
        bundle_dict = bundle.to_dict()

        # Persist evidence to database
        try:
            evidence_items = getattr(analysis, "evidence_items", []) or []
            for i, ev in enumerate(evidence_items[:5]):
                ev_record = models.Evidence(
                    finding_id=finding.id,
                    endpoint_id=endpoint.id,
                    attempt_label=f"probe_{i + 1}",
                    request_url=getattr(analysis, "endpoint", ""),
                    request_method=getattr(analysis, "method", "GET"),
                    request_headers=None,
                    request_params=None,
                    request_body=None,
                    response_status=200,
                    response_headers=None,
                    response_body=ev.get("detail", ""),
                    curl_command=bundle.curl_command,
                    status_match="true",
                    body_diff_ratio=str(cvss / 10.0),
                    consistent="true",
                )
                session.add(ev_record)
            session.commit()
            logger.info(
                "[EVIDENCE] Persisted %d evidence records for finding #%d",
                min(len(evidence_items), 5),
                finding.id,
            )
        except Exception as e:
            logger.debug("[EVIDENCE] Could not persist evidence records: %s", e)
            session.rollback()

        return bundle_dict

    except Exception as e:
        logger.warning("[EVIDENCE] Failed to compose evidence for finding #%d: %s", finding.id, e)
        # Notify about evidence composition failure
        try:
            from cores.notifications.action_required import notify_action_required

            notify_action_required(
                title=f"Evidence composition failed for finding #{finding.id}",
                reason=str(e),
                impact="Finding confirmed but evidence bundle incomplete — report may not be submission-ready",
                steps=[
                    f"Go to Findings > #{finding.id}",
                    "Review probe results manually",
                    "Compose evidence manually if needed",
                    "Mark as ready when complete",
                ],
                ui_path="/intelligence/findings",
                category="review",
                priority="medium",
                channels=["web"],
                subject_id=str(finding.id),
                subject_type="finding",
            )
        except Exception:
            pass
        return None


def _generate_report_for_finding(
    session: Any,
    finding: models.Finding,
    evidence_bundle: dict[str, Any],
) -> models.Report | None:
    """Generate a report record for a confirmed finding."""
    try:
        from database.models import Report

        bundle_data = evidence_bundle.get("report_body", {})
        scoring = evidence_bundle.get("scoring", {})

        report = Report(
            finding_ids=str(finding.id),
            severity=finding.severity or "medium",
            vulnerability=finding.vulnerability_type or "unknown",
            status="draft",
            content=json.dumps(evidence_bundle, default=str),
            program=_get_platform_for_target(finding.target_id, session),
            target="",
            evidence_count=len(bundle_data.get("reproduction_steps", [])),
            notes=json.dumps(
                {
                    "cvss_score": scoring.get("cvss_score", 0.0),
                    "cwe_id": scoring.get("cwe_id", ""),
                    "poc_curl": evidence_bundle.get("poc", {}).get("curl", ""),
                    "poc_python": evidence_bundle.get("poc", {}).get("python", ""),
                    "poc_javascript": evidence_bundle.get("poc", {}).get("javascript", ""),
                    "remediation": _get_remediation_for_type(finding.vulnerability_type),
                    "is_ready": evidence_bundle.get("readiness", {}).get("is_report_ready", False),
                }
            ),
        )
        session.add(report)
        session.commit()
        session.refresh(report)

        logger.info(
            "[REPORT] Generated report #%d for finding #%d (ready=%s)",
            report.id,
            finding.id,
            evidence_bundle.get("readiness", {}).get("is_report_ready", False),
        )

        _publish_event(
            "report:generated",
            {
                "report_id": report.id,
                "finding_id": finding.id,
                "vulnerability_type": finding.vulnerability_type,
                "is_ready": evidence_bundle.get("readiness", {}).get("is_report_ready", False),
            },
        )

        return report

    except Exception as e:
        logger.warning("[REPORT] Failed to generate report for finding #%d: %s", finding.id, e)
        session.rollback()
        return None


def _get_remediation_for_type(vuln_type: str | None) -> str:
    """Get standard remediation guidance for a vulnerability type."""
    remediations = {
        "idor": "Implement proper authorization checks for every object access. Verify the authenticated user has permission to access the requested resource ID.",
        "ssrf": "Validate and sanitize all user-supplied URLs. Use allowlists for permitted domains. Block requests to internal IP ranges and cloud metadata endpoints.",
        "xss": "Apply context-aware output encoding. Implement Content Security Policy (CSP). Validate and sanitize all user input before rendering.",
        "sqli": "Use parameterized queries or prepared statements. Never concatenate user input into SQL queries. Apply principle of least privilege to database accounts.",
        "auth_bypass": "Verify authentication on every protected endpoint. Implement proper session management. Use multi-factor authentication for sensitive operations.",
    }
    return remediations.get(
        vuln_type or "", "Review and remediate the identified vulnerability following industry best practices."
    )


def _get_platform_for_target(target_id: int | None, session: Any) -> str:
    """Get the bounty platform for a target."""
    if not target_id:
        return "hackerone"
    try:
        from database.models import Program, Target

        target = session.query(Target).filter(Target.id == target_id).first()
        if target and target.program_id:
            program = session.query(Program).filter(Program.id == target.program_id).first()
            if program and program.platform:
                return program.platform
    except Exception:
        pass
    return "hackerone"


def _infer_vuln_type_from_endpoint(endpoint: Any, target: Any) -> str | None:
    """Infer vulnerability type from endpoint characteristics.

    First checks path patterns (matching _path_based_hypothesis logic),
    then falls back to parameter-based inference.
    """
    path = (getattr(endpoint, "path", "") or "").lower()
    params = (endpoint.parsed_params or {}) if hasattr(endpoint, "parsed_params") else {}
    method = (getattr(endpoint, "method", "GET") or "GET").upper()

    param_keys = list(params.keys()) if isinstance(params, dict) else []

    # Path-based inference (mirrors _path_based_hypothesis from scheduler)
    if path.endswith("/graphql") or "/graphql?" in path:
        return "graphql_injection"

    if "/upload" in path or "/file" in path or "multipart" in path:
        return "file_upload"

    if "/admin" in path or "/login" in path or "/auth" in path:
        return "auth_bypass"

    # Parameter-based inference
    id_patterns = ["id", "user_id", "account_id", "profile_id", "uid", "userId", "ID"]
    if any(k.lower() in id_patterns for k in param_keys) and method in ("GET", "DELETE"):
        return "idor"

    if any(
        k.lower().startswith("url") or k.lower().startswith("redirect") or k in ("next", "path") for k in param_keys
    ):
        return "ssrf"

    if any(k.lower() in ("q", "query", "search", "s") for k in param_keys) and method in ("GET", "POST"):
        return "xss"

    if "search" in path:
        return "xss"

    return None


def run_promote_and_report(session: Any) -> dict[str, Any]:
    """Run promote and return a formatted report dict."""
    stats = run_promote(session)
    summary = {
        "stage": "promote",
        "total_findings_created": stats["findings_created"],
        "total_hypotheses_tested": stats["hypotheses_tested"],
        "total_endpoints_checked": stats["endpoints_checked"],
        "failed": stats["failed"],
        "elapsed_seconds": stats.get("elapsed_seconds", 0),
    }
    return summary
