var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/fallback/chains/route.js")
R.c("server/chunks/_0e6xqss._.js")
R.c("server/chunks/[root-of-the-server]__0ob5f1e._.js")
R.c("server/chunks/src_shared_04v-ucl._.js")
R.c("server/chunks/src_shared_0p0h6qs._.js")
R.c("server/chunks/[root-of-the-server]__1sdgs2d._.js")
R.c("server/chunks/[root-of-the-server]__0oxznu7._.js")
R.c("server/chunks/src_1akg35a._.js")
R.c("server/chunks/node_modules_next_dist_13kw1hb._.js")
R.c("server/chunks/node_modules_next_1zdbrne._.js")
R.c("server/chunks/src_shared_1p2xeml._.js")
R.c("server/chunks/[root-of-the-server]__1jxfxmi._.js")
R.c("server/chunks/_next-internal_server_app_api_fallback_chains_route_actions_1iisq2d.js")
R.m(245305)
module.exports=R.m(245305).exports
